### ISSUE TITLE
Terraform always replaces ECS task definition

### ISSUE THREAD

**Issue by olivermeyer** [secoda/terraform-aws-secoda#1]
Terraform consistently wants to replace an ECS task definition, although no changes were made to the task definition. This pollutes our Terraform plans.
```
  # module.secoda.module.ecs.aws_ecs_task_definition.main must be replaced
-/+ resource "aws_ecs_task_definition" "main" {
      ~ arn                      = "[REDACTED]:task-definition/secoda:51" -> (known after apply)
      ~ container_definitions    = (sensitive) # forces replacement
      ~ id                       = "secoda" -> (known after apply)
      - ipc_mode                 = "" -> null
      - pid_mode                 = "" -> null
      ~ revision                 = 51 -> (known after apply)
      - tags                     = {} -> null
      ~ tags_all                 = {} -> (known after apply)
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
There is a [known issue](https://github.com/hashicorp/terraform-provider-aws/issues/11526) affecting ECS task definitions with mount points, which could be the cause. There are also a handful of workarounds in the same GitHub issue but I haven't had time to test any of them.

Steps to reproduce:
* `terraform plan` in any workspace containing a Secoda installation

**Comment by LikeCarter** [comment]
Thanks @olivermeyer - I've put out a fix now.

**Comment by olivermeyer** [comment]
That worked, thanks for the quick fix @LikeCarter!
